
[tasks.systembruker]
description = "Hent token"
usage = '''
arg "<tjeneste>" help="Tjenesten man skal hente systembruker for (narmesteleder, dialogporten)" {
  choices "narmesteleder" "dialogporten"
}
arg "<organisasjonsnummer>" help="Organisasjonsnummeret man skal ha systembruker for"
'''

run = '''
curl -sS "https://esyfo-token.intern.dev.nav.no/systembruker/${usage_tjeneste}/${usage_organisasjonsnummer}"
'''

[tasks.nl]
description = "Hent token for narmesteleder"
usage = '''
arg "<organisasjonsnummer>" help="Organisasjonsnummeret man skal ha systembruker for"
'''

run = '''
mise systembruker narmesteleder "${usage_organisasjonsnummer}"
'''

[tasks.dokporten]
description = "Hent token for dokumentporten"
usage = '''
arg "<organisasjonsnummer>" help="Organisasjonsnummeret man skal ha systembruker for"
'''

run = '''
mise systembruker dokumentporten "${usage_organisasjonsnummer}"
'''

[tasks.test]
description = "Run tests with gradle"
run = './gradlew test'

[tasks.lint]
description = "Run check with gradle"
run = './gradlew ktlintCheck'

[tasks.format]
description = "Run ktlintFormat with gradle"
run = './gradlew ktlintFormat'

[tasks."gh:refresh"]
description = "Refresh token with packages scope. Used to fetch gradle deps."
run = 'gh auth refresh --scopes read:packages && export ORG_GRADLE_PROJECT_githubPassword=$(gh auth token)'

[tasks."gh:token"]
description = "Add token to env vars"
run = 'export ORG_GRADLE_PROJECT_githubPassword=$(gh auth token)'

[tasks.assemble]
description = "Assemble the project with gradle. Make sure you have ran gh:token first"
run = './gradlew assemble'

[tasks.build]
description = "Build the project with gradle. Make sure you have ran gh:token first"
run = './gradlew build -x test'
